// Generated by eBay Common SDK Platform
package com.ctrip.soa.global.api.exchangepriceinfo.v1;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * 价格种类
 */
@XmlType(name = "ExchangePriceInfoType")
@XmlEnum
@SuppressWarnings("all")
public enum ExchangePriceInfoType {

    /**
     * 
   *               默认为None
   *             
     */
    @XmlEnumValue("None")
    None(0, "None"),

    /**
     * 
   *               外卡手续费
   *             
     */
    @XmlEnumValue("CCardFee")
    CCardFee(1, "CCardFee");

    private final int intValue;
    private final String value;

    ExchangePriceInfoType(int intValue, String value) {
        this.intValue = intValue;
        this.value = value;
    }

    public int getValue() {
        return intValue;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @JsonCreator
    public static ExchangePriceInfoType fromValue(String v) {
        for (ExchangePriceInfoType e: ExchangePriceInfoType.values()) {
            if (e.value.equals(v)) {
                return e;
            }
        }
        throw new IllegalArgumentException(v);
    }

    public static ExchangePriceInfoType findByValue(int value) {
        switch (value) {
            case 0:
                return None;
            case 1:
                return CCardFee;
            default:
                return null;
        }
    }
}